### ISSUE TITLE
App not functioning properly with new firmware

### ISSUE THREAD

**Issue by Nathanvs** [fedorcomander/simple-gui#5]
After upgrading my KISS fc to v1.1RC6 using the android app seems to change the fc rotation, battery voltage beeper setting and changes the arm and buzzer settings to nothing. Changing the arm and buzzer settings in the android app also don't seem to work anymore when tried with the transmitter although seem to look fine in the android app when changing them. These cannot be fixed properly without going back to the chrome app. I have tried v1.0.4 and v1.0.2 of the android app and the problems still occur. I am guessing it is the new functions of the firmware which is causing the issue.

**Comment by fedorcomander** [comment]
Upgrade app to 1.14.

**Comment by fedorcomander** [comment]
https://github.com/fedorcomander/kissfc-chrome-gui/releases/tag/v1.14

**Comment by fedorcomander** [comment]
Btw, this project is absolete anyways.

**Comment by Nathanvs** [comment]
My chrome app is 1.14, but can I ask the reasoning for leaving the project?

**Comment by fedorcomander** [comment]
Its not abandoned. I am using chrome gui code for all platforms… :)))) Before it was fork and pain to maintain ;)
